(()=>{
const PENDING_KEY='naturalCastanhasPendingUsersV1';
const USERS_KEY='naturalCastanhasAuthUsersV1';
const AUDIT_KEY='naturalCastanhasAuditV1';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const now=()=>new Date().toLocaleString('pt-BR');
const getPending=()=>JSON.parse(localStorage.getItem(PENDING_KEY)||'[]');
const setPending=v=>localStorage.setItem(PENDING_KEY,JSON.stringify(v));
const getUsers=()=>JSON.parse(localStorage.getItem(USERS_KEY)||'[]');
const setUsers=v=>localStorage.setItem(USERS_KEY,JSON.stringify(v));
function current(){return window.NaturalCastanhasAuth?.currentUser?.()||null}
function isAdmin(u){return !!u&&(u.role==='Administrador'||u.role==='Administrador proprietário'||u.canApprove===true)}
function audit(action,detail){const list=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');list.unshift({id:String(Date.now()),date:now(),user:current()?.name||'Administrador',action,detail});localStorage.setItem(AUDIT_KEY,JSON.stringify(list.slice(0,100)))}
function style(){if(document.getElementById('admin-center-style'))return;const s=document.createElement('style');s.id='admin-center-style';s.textContent=`.admin-alert{background:#fff8df;border:1px solid #ecd98d;border-radius:16px;padding:14px;margin:14px 0}.admin-alert strong{display:block;font-size:1.1rem}.admin-pending-list{display:grid;gap:12px}.admin-request{background:#fff;border:1px solid #dde7de;border-radius:16px;padding:14px;box-shadow:0 6px 20px rgba(26,70,33,.06)}.admin-request h3{margin:0 0 5px}.admin-request small{color:#6d786f}.admin-request .requested-role{display:inline-block;margin-top:9px;background:#e8f4ea;color:#24552a;border-radius:999px;padding:6px 9px;font-weight:800}.admin-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.admin-actions button{border:0;border-radius:10px;padding:10px 12px;font-weight:800}.admin-approve{background:#24552a;color:#fff}.admin-change{background:#edf3ee;color:#24552a}.admin-reject{background:#fde9e7;color:#9b2f28}.admin-empty{text-align:center;padding:28px;color:#748077}.admin-badge{display:inline-grid;place-items:center;min-width:24px;height:24px;padding:0 7px;border-radius:999px;background:#b7372f;color:#fff;font-size:.75rem;font-weight:900;margin-left:6px}`;document.head.appendChild(s)}
function openView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo({top:0,behavior:'smooth'})}
function injectView(){if(document.getElementById('adminCenterView'))return;const main=document.querySelector('.app-shell');if(!main)return;const v=document.createElement('section');v.id='adminCenterView';v.className='view';v.innerHTML=`<div class="module-header"><button class="back-button" id="adminCenterBack">←</button><div><p class="eyebrow">Administração</p><h1>Central do Administrador</h1></div></div><section class="admin-alert"><strong id="adminPendingSummary">0 solicitações pendentes</strong><span>Analise os cadastros antes de liberar o acesso ao aplicativo.</span></section><div class="admin-pending-list" id="adminPendingList"></div>`;main.appendChild(v);document.getElementById('adminCenterBack').onclick=()=>openView('usersView')}
function injectAccess(){const u=current();if(!isAdmin(u))return;const view=document.getElementById('usersView');if(view&&!document.getElementById('openAdminCenter')){const note=view.querySelector('.n11-note');const b=document.createElement('button');b.id='openAdminCenter';b.className='primary-button';b.style.margin='0 0 14px';b.innerHTML=`Solicitações de acesso <span class="admin-badge" id="adminPendingBadge">0</span>`;b.onclick=()=>{openView('adminCenterView');render()};note?.insertAdjacentElement('afterend',b)}const home=document.getElementById('homeView');if(home&&!document.getElementById('homeAdminCard')){const card=document.createElement('section');card.id='homeAdminCard';card.className='summary-card';card.style.marginBottom='18px';card.innerHTML=`<div class="card-heading"><div><p class="eyebrow light">Administração</p><h2>Central do Administrador</h2></div><span class="status-dot" id="homePendingCount">0 pendentes</span></div><p style="margin:16px 0">Aprove, altere o perfil ou recuse solicitações de acesso.</p><button class="primary-button" id="homeOpenAdmin">Abrir solicitações</button>`;home.querySelector('#nucleo0Status')?.insertAdjacentElement('afterend',card);document.getElementById('homeOpenAdmin').onclick=()=>{openView('adminCenterView');render()}}}
function profileOptions(selected){return ['Administrador','Compras','Capital e Investidores','Fornecedores','Estoque','Vendas','Financeiro','Resultados','Logística','Relatórios','Documentos e Conformidade','Consulta'].map(r=>`<option ${r===selected?'selected':''}>${r}</option>`).join('')}
function approve(id,role){const pending=getPending(),request=pending.find(x=>x.id===id);if(!request)return;const users=getUsers();const existing=users.find(u=>u.id===`request-${id}`);const user={id:`request-${id}`,name:request.name,email:request.email,phone:request.phone,role,approved:true,activated:false,status:'Aprovado — aguardando criação de senha',canApprove:role==='Administrador',permissions:role==='Administrador'?['Todos os núcleos','Usuários e permissões','Auditoria','Configurações']:[],createdAt:request.createdAt,approvedAt:new Date().toISOString(),approvedBy:current()?.name||'Administrador'};if(existing)Object.assign(existing,user);else users.push(user);setUsers(users);request.status='Aprovado';request.approvedRole=role;request.approvedAt=new Date().toISOString();setPending(pending);audit('Acesso aprovado',`${request.name} aprovado no perfil ${role}.`);render();alert(`${request.name} foi aprovado como ${role}. Agora poderá criar a própria senha em “Ativar acesso aprovado”.`)}
function reject(id){const pending=getPending(),r=pending.find(x=>x.id===id);if(!r)return;if(!confirm(`Recusar o acesso solicitado por ${r.name}?`))return;r.status='Recusado';r.reviewedAt=new Date().toISOString();setPending(pending);audit('Acesso recusado',r.name);render()}
function render(){const list=getPending().filter(x=>x.status==='Aguardando aprovação');const el=document.getElementById('adminPendingList');if(el)el.innerHTML=list.length?list.map(r=>`<article class="admin-request"><h3>${esc(r.name)}</h3><small>${esc(r.email||r.phone||'Contato não informado')} • ${new Date(r.createdAt).toLocaleString('pt-BR')}</small><div><span class="requested-role">Solicitou: ${esc(r.requestedRole)}</span></div><div class="admin-actions"><button class="admin-approve" data-approve="${r.id}">Aprovar</button><button class="admin-change" data-change="${r.id}">Alterar perfil</button><button class="admin-reject" data-reject="${r.id}">Recusar</button></div></article>`).join(''):'<div class="admin-empty">Nenhuma solicitação aguardando aprovação.</div>';document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>{const r=list.find(x=>x.id===b.dataset.approve);approve(r.id,r.requestedRole)});document.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>{const r=list.find(x=>x.id===b.dataset.change);const wrap=document.createElement('dialog');wrap.innerHTML=`<form method="dialog" class="n11-form" style="min-width:min(88vw,380px)"><h2>Alterar perfil</h2><label>Perfil autorizado<select id="adminRoleSelect">${profileOptions(r.requestedRole)}</select></label><div class="admin-actions"><button value="cancel" class="admin-change">Cancelar</button><button value="default" class="admin-approve" id="adminConfirmRole">Aprovar perfil</button></div></form>`;document.body.appendChild(wrap);wrap.addEventListener('close',()=>wrap.remove());wrap.querySelector('#adminConfirmRole').onclick=e=>{e.preventDefault();approve(r.id,wrap.querySelector('#adminRoleSelect').value);wrap.close()};wrap.showModal()});document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reject(b.dataset.reject));const count=list.length;const summary=document.getElementById('adminPendingSummary');if(summary)summary.textContent=`${count} ${count===1?'solicitação pendente':'solicitações pendentes'}`;const badge=document.getElementById('adminPendingBadge');if(badge)badge.textContent=count;const home=document.getElementById('homePendingCount');if(home)home.textContent=`${count} pendente${count===1?'':'s'}`}
function init(){style();injectView();setTimeout(()=>{injectAccess();render()},650)}
document.addEventListener('nc-auth-ready',()=>setTimeout(()=>{injectAccess();render()},120));document.addEventListener('nc-pending-updated',render);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();