(()=>{
const USERS_KEY='naturalCastanhasAuthUsersV1';
const SESSION_KEY='naturalCastanhasAuthSessionV1';
const PENDING_KEY='naturalCastanhasPendingUsersV1';
const ADMINS=[
 {id:'tiago',name:'Tiago Pereira de Albuquerque',role:'Administrador proprietário'},
 {id:'helio',name:'Hélio',role:'Administrador proprietário'}
];
const enc=new TextEncoder();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const getUsers=()=>JSON.parse(localStorage.getItem(USERS_KEY)||'[]');
const setUsers=v=>localStorage.setItem(USERS_KEY,JSON.stringify(v));
const getSession=()=>JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');
const setSession=v=>sessionStorage.setItem(SESSION_KEY,JSON.stringify(v));
const hash=async(text)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(text)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const salt=()=>crypto.getRandomValues(new Uint32Array(4)).join('-');
function seed(){const users=getUsers();ADMINS.forEach(a=>{if(!users.some(u=>u.id===a.id))users.push({...a,status:'Pré-cadastrado',activated:false,passwordHash:'',salt:''})});setUsers(users)}
function currentUser(){const s=getSession();return s?getUsers().find(u=>u.id===s.userId)||null:null}
function applyIdentity(user){document.documentElement.dataset.authenticated='true';window.NaturalCastanhasAuth={currentUser:()=>user,logout};document.querySelectorAll('[data-current-user]').forEach(e=>e.textContent=user.name);document.querySelectorAll('[data-current-role]').forEach(e=>e.textContent=user.role);const profile=document.getElementById('profileView');if(profile){const h=profile.querySelector('h2');if(h)h.textContent=user.name;profile.querySelectorAll('strong').forEach(el=>{if(el.textContent==='Hélio'||el.textContent==='Tiago e Hélio')el.textContent=user.name;if(el.textContent==='Administrador')el.textContent=user.role})}}
function logout(){sessionStorage.removeItem(SESSION_KEY);location.reload()}
function style(){if(document.getElementById('auth-style'))return;const s=document.createElement('style');s.id='auth-style';s.textContent=`#authGate{position:fixed;inset:0;z-index:100000;background:linear-gradient(160deg,#163d20,#2e6a35);display:grid;place-items:center;padding:20px;overflow:auto}.auth-card{width:min(100%,430px);background:#fff;border-radius:24px;padding:24px;box-shadow:0 24px 60px rgba(0,0,0,.28)}.auth-logo{width:82px;height:82px;border-radius:20px;object-fit:cover;display:block;margin:0 auto 14px}.auth-card h1,.auth-card h2{text-align:center;margin:8px 0}.auth-card p{color:#68736a;line-height:1.5}.auth-tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.auth-tabs button,.auth-choice,.auth-submit,.auth-link{border:0;border-radius:12px;padding:12px;font-weight:800}.auth-tabs button{background:#eef3ef;color:#24552a}.auth-tabs button.active,.auth-submit{background:#24552a;color:#fff}.auth-form{display:grid;gap:12px}.auth-form label{display:grid;gap:6px;font-weight:700}.auth-form input,.auth-form select{border:1px solid #ccd7ce;border-radius:12px;padding:12px;font:inherit;width:100%}.auth-note{background:#fff8df;border:1px solid #eedb9c;border-radius:12px;padding:11px;color:#6b5720;font-size:.9rem}.auth-error{color:#9b2f28;font-weight:700;min-height:20px}.auth-link{background:transparent;color:#24552a}.auth-actions{display:flex;gap:8px;flex-wrap:wrap}.auth-actions>*{flex:1}`;document.head.appendChild(s)}
function gate(){style();const root=document.createElement('div');root.id='authGate';root.innerHTML=`<div class="auth-card"><img class="auth-logo" src="141FEC0C-C074-45A3-84B5-4538207A5C5E.png" alt="Natural Castanhas"><h1>Natural Castanhas</h1><p style="text-align:center">Acesso seguro ao aplicativo</p><div class="auth-tabs"><button class="active" data-tab="login">Entrar</button><button data-tab="register">Primeiro cadastro</button></div><div id="authContent"></div></div>`;document.body.appendChild(root);root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.tab)});render('login')}
function render(tab){const c=document.getElementById('authContent');if(tab==='register')return renderRegister(c);const users=getUsers();c.innerHTML=`<form id="loginForm" class="auth-form"><label>Usuário<select name="userId" required><option value="">Selecione</option>${users.filter(u=>u.activated).map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label><label>Senha<input name="password" type="password" minlength="6" required autocomplete="current-password"></label><div class="auth-error" id="loginError"></div><button class="auth-submit">Entrar</button><button type="button" class="auth-link" id="activateAdmin">Ativar conta de administrador</button></form>`;document.getElementById('loginForm').onsubmit=login;document.getElementById('activateAdmin').onclick=()=>renderActivate(c)}
function renderActivate(c){const users=getUsers().filter(u=>ADMINS.some(a=>a.id===u.id)&&!u.activated);c.innerHTML=`<form id="activateForm" class="auth-form"><h2>Ativar administrador</h2><div class="auth-note">Cada administrador cria sua própria senha neste aparelho. A senha não é enviada ao GitHub.</div><label>Administrador<select name="userId" required><option value="">Selecione</option>${users.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label><label>Criar senha<input name="password" type="password" minlength="6" required></label><label>Confirmar senha<input name="confirm" type="password" minlength="6" required></label><div class="auth-error" id="activateError"></div><div class="auth-actions"><button class="auth-submit">Ativar conta</button><button type="button" class="auth-link" id="backLogin">Voltar</button></div></form>`;document.getElementById('backLogin').onclick=()=>render('login');document.getElementById('activateForm').onsubmit=activate}
async function activate(e){e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('userId'),p=String(f.get('password')),confirm=String(f.get('confirm')),err=document.getElementById('activateError');if(p!==confirm){err.textContent='As senhas não coincidem.';return}const users=getUsers(),u=users.find(x=>x.id===id);if(!u||u.activated){err.textContent='Conta indisponível para ativação.';return}u.salt=salt();u.passwordHash=await hash(u.salt+p);u.activated=true;u.status='Ativo';u.updatedAt=new Date().toISOString();setUsers(users);setSession({userId:u.id,createdAt:new Date().toISOString()});document.getElementById('authGate').remove();applyIdentity(u)}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),u=getUsers().find(x=>x.id===f.get('userId')),err=document.getElementById('loginError');if(!u){err.textContent='Selecione um usuário.';return}if(await hash(u.salt+String(f.get('password')))!==u.passwordHash){err.textContent='Senha incorreta.';return}setSession({userId:u.id,createdAt:new Date().toISOString()});document.getElementById('authGate').remove();applyIdentity(u)}
function renderRegister(c){c.innerHTML=`<form id="registerForm" class="auth-form"><h2>Solicitar acesso</h2><label>Nome completo<input name="name" required></label><label>Telefone<input name="phone" required></label><label>E-mail<input name="email" type="email"></label><label>Perfil solicitado<select name="role"><option>Compras</option><option>Financeiro</option><option>Estoque</option><option>Comercial</option><option>Logística</option><option>Consulta</option></select></label><div class="auth-note">O acesso ficará aguardando aprovação de Tiago ou Hélio no Núcleo 11.</div><div class="auth-error" id="registerError"></div><button class="auth-submit">Enviar cadastro</button></form>`;document.getElementById('registerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),list=JSON.parse(localStorage.getItem(PENDING_KEY)||'[]');list.push({id:String(Date.now()),name:f.get('name').trim(),phone:f.get('phone').trim(),email:f.get('email').trim(),requestedRole:f.get('role'),status:'Aguardando aprovação',createdAt:new Date().toISOString()});localStorage.setItem(PENDING_KEY,JSON.stringify(list));document.getElementById('registerError').style.color='#24552a';document.getElementById('registerError').textContent='Cadastro enviado. Aguarde aprovação de um administrador.';e.currentTarget.reset()}}
function addAccountControls(){const profile=document.getElementById('profileView');if(!profile||document.getElementById('authAccountControls'))return;const box=document.createElement('section');box.id='authAccountControls';box.className='summary-card';box.style.marginTop='18px';box.innerHTML=`<div class="card-heading"><div><p class="eyebrow light">Segurança da conta</p><h2>Senha e sessão</h2></div></div><div class="dual-actions" style="margin-top:16px"><button class="primary-button" id="changePasswordButton">Trocar senha</button><button class="secondary-button wide" id="logoutButton">Sair da conta</button></div>`;profile.appendChild(box);document.getElementById('logoutButton').onclick=logout;document.getElementById('changePasswordButton').onclick=changePassword}
async function changePassword(){const u=currentUser();if(!u)return;const current=prompt('Digite a senha atual:');if(current===null)return;if(await hash(u.salt+current)!==u.passwordHash)return alert('Senha atual incorreta.');const next=prompt('Digite a nova senha com pelo menos 6 caracteres:');if(!next||next.length<6)return alert('A nova senha precisa ter pelo menos 6 caracteres.');const confirm=prompt('Confirme a nova senha:');if(next!==confirm)return alert('As senhas não coincidem.');const users=getUsers(),target=users.find(x=>x.id===u.id);target.salt=salt();target.passwordHash=await hash(target.salt+next);target.updatedAt=new Date().toISOString();setUsers(users);alert('Senha alterada com sucesso.')}
function init(){seed();const u=currentUser();if(u)applyIdentity(u);else gate();setTimeout(addAccountControls,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();