(()=>{
const PENDING_KEY='naturalCastanhasPendingUsersV1';
const onlyDigits=v=>String(v||'').replace(/\D/g,'');
const formatCPF=v=>onlyDigits(v).slice(0,11).replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2');
const formatCNPJ=v=>onlyDigits(v).slice(0,14).replace(/^(\d{2})(\d)/,'$1.$2').replace(/^(\d{2})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1/$2').replace(/(\d{4})(\d{1,2})$/,'$1-$2');
const formatCEP=v=>onlyDigits(v).slice(0,8).replace(/(\d{5})(\d{1,3})$/,'$1-$2');
function validCPF(value){const cpf=onlyDigits(value);if(cpf.length!==11||/^(\d)\1+$/.test(cpf))return false;for(let t=9;t<11;t++){let sum=0;for(let i=0;i<t;i++)sum+=Number(cpf[i])*((t+1)-i);let d=(sum*10)%11;if(d===10)d=0;if(d!==Number(cpf[t]))return false}return true}
function validCNPJ(value){const cnpj=onlyDigits(value);if(cnpj.length!==14||/^(\d)\1+$/.test(cnpj))return false;const calc=base=>{let p=base.length-7,sum=0;for(const n of base){sum+=Number(n)*p--;if(p<2)p=9}const r=sum%11;return r<2?0:11-r};return calc(cnpj.slice(0,12))===Number(cnpj[12])&&calc(cnpj.slice(0,13))===Number(cnpj[13])}
function fields(type){if(type==='PJ')return `<label>Razão social<input name="companyName" required autocomplete="organization"></label><label>Nome fantasia<input name="tradeName" autocomplete="organization-title"></label><label>CNPJ<input name="document" inputmode="numeric" maxlength="18" required placeholder="00.000.000/0000-00"></label><label>Nome do responsável<input name="name" required autocomplete="name"></label><label>Cargo do responsável<input name="responsibleRole" required></label>`;return `<label>Nome completo<input name="name" required autocomplete="name"></label><label>CPF<input name="document" inputmode="numeric" maxlength="14" required placeholder="000.000.000-00"></label><label>Data de nascimento<input name="birthDate" type="date" required></label>`}
function enhance(){const form=document.getElementById('registerForm');if(!form||form.dataset.pfPj==='1')return;form.dataset.pfPj='1';const roles=['Administrador','Compras','Capital e Investidores','Fornecedores','Estoque','Vendas','Financeiro','Resultados','Logística','Relatórios','Documentos e Conformidade','Consulta'];form.innerHTML=`<h2>Solicitar acesso</h2><label>Tipo de cadastro<select name="personType" id="personType" required><option value="PF">Pessoa física — CPF</option><option value="PJ">Pessoa jurídica — CNPJ</option></select></label><div id="personFields" class="auth-form"></div><label>Telefone<input name="phone" inputmode="tel" required autocomplete="tel"></label><label>E-mail<input name="email" type="email" required autocomplete="email"></label><label>CEP<input name="cep" inputmode="numeric" maxlength="9" required placeholder="00000-000"></label><label>Endereço<input name="address" required autocomplete="street-address"></label><label>Cidade<input name="city" required></label><label>Estado<select name="state" required><option value="">Selecione</option>${['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Perfil solicitado<select name="role">${roles.map(r=>`<option>${r}</option>`).join('')}</select></label><div class="auth-note">Inclusive o perfil Administrador depende de aprovação. Quando aprovado, terá acesso a todos os núcleos e poderá autorizar outros usuários.</div><div class="auth-error" id="registerError"></div><button class="auth-submit">Enviar cadastro</button>`;
const type=form.querySelector('#personType'),holder=form.querySelector('#personFields');
const draw=()=>{holder.innerHTML=fields(type.value);const doc=holder.querySelector('[name="document"]');doc.addEventListener('input',()=>doc.value=type.value==='PJ'?formatCNPJ(doc.value):formatCPF(doc.value))};draw();type.onchange=draw;const cep=form.querySelector('[name="cep"]');cep.oninput=()=>cep.value=formatCEP(cep.value);
form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),personType=String(f.get('personType')),documentValue=String(f.get('document'));const err=form.querySelector('#registerError');if(personType==='PF'&&!validCPF(documentValue)){err.textContent='Informe um CPF válido.';return}if(personType==='PJ'&&!validCNPJ(documentValue)){err.textContent='Informe um CNPJ válido.';return}const list=JSON.parse(localStorage.getItem(PENDING_KEY)||'[]');const item={id:String(Date.now()),personType,document:onlyDigits(documentValue),documentFormatted:personType==='PJ'?formatCNPJ(documentValue):formatCPF(documentValue),name:String(f.get('name')).trim(),companyName:String(f.get('companyName')||'').trim(),tradeName:String(f.get('tradeName')||'').trim(),responsibleRole:String(f.get('responsibleRole')||'').trim(),birthDate:String(f.get('birthDate')||''),phone:String(f.get('phone')).trim(),email:String(f.get('email')).trim(),cep:onlyDigits(f.get('cep')),address:String(f.get('address')).trim(),city:String(f.get('city')).trim(),state:String(f.get('state')),requestedRole:String(f.get('role')),status:'Aguardando aprovação',createdAt:new Date().toISOString()};list.push(item);localStorage.setItem(PENDING_KEY,JSON.stringify(list));document.dispatchEvent(new Event('nc-pending-updated'));err.style.color='#24552a';err.textContent='Cadastro enviado. Aguarde a aprovação de um administrador.';form.reset();draw()}}
function enrichAdmin(){const pending=JSON.parse(localStorage.getItem(PENDING_KEY)||'[]').filter(x=>x.status==='Aguardando aprovação');document.querySelectorAll('.admin-request').forEach((card,index)=>{if(card.querySelector('.registration-details'))return;const r=pending[index];if(!r)return;const box=document.createElement('div');box.className='registration-details';box.style.cssText='margin-top:10px;padding:10px;border-radius:12px;background:#f4f7f4;font-size:.88rem;line-height:1.5';const identity=r.personType==='PJ'?`Pessoa jurídica • CNPJ ${r.documentFormatted||r.document}<br><strong>${r.companyName||''}</strong>${r.tradeName?` — ${r.tradeName}`:''}<br>Responsável: ${r.name}${r.responsibleRole?` (${r.responsibleRole})`:''}`:`Pessoa física • CPF ${r.documentFormatted||r.document}<br><strong>${r.name}</strong>${r.birthDate?` • Nascimento: ${new Date(r.birthDate+'T12:00:00').toLocaleDateString('pt-BR')}`:''}`;box.innerHTML=`${identity}<br>${r.phone||''}${r.email?` • ${r.email}`:''}<br>${r.address||''}${r.city?` — ${r.city}/${r.state}`:''}${r.cep?` • CEP ${formatCEP(r.cep)}`:''}`;card.querySelector('.requested-role')?.parentElement?.insertAdjacentElement('afterend',box)})}
const observer=new MutationObserver(()=>{enhance();enrichAdmin()});observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',()=>{enhance();enrichAdmin()});document.addEventListener('nc-pending-updated',()=>setTimeout(enrichAdmin,30));
})();