(()=>{
const KEY='naturalCastanhasFinanceEntries',ACCOUNTS_KEY='naturalCastanhasFinanceAccounts';
const q=s=>document.querySelector(s),n=v=>Number(v||0),money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n(v)),date=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—',uid=()=>String(Date.now())+Math.random().toString(16).slice(2,6);
let entries=JSON.parse(localStorage.getItem(KEY)||'[]');
let accounts=JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||'[]');
if(!accounts.length)accounts=[{id:'caixa',name:'Caixa físico',type:'Caixa',initial:0},{id:'banco',name:'Conta bancária',type:'Banco',initial:0}];
const save=()=>{localStorage.setItem(KEY,JSON.stringify(entries));localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(accounts));renderFinance()};
function derived(){const ps=JSON.parse(localStorage.getItem('naturalCastanhasPurchases')||'[]'),ss=JSON.parse(localStorage.getItem('naturalCastanhasSales')||'[]'),out=[],inside=[];ps.filter(p=>p.status!=='Cancelada').forEach(p=>(p.payments||[]).forEach(x=>out.push({id:`purchase-${p.id}-${x.id}`,date:x.date,type:'Saída',category:'Pagamento a fornecedor',description:`Fornecedor: ${p.supplier}`,amount:n(x.amount),account:'banco',source:'Compra',automatic:true})));ss.filter(s=>s.status!=='Cancelada').forEach(s=>(s.history||[]).filter(h=>h.amount).forEach((h,i)=>inside.push({id:`sale-${s.id}-${i}`,date:h.date,type:'Entrada',category:'Recebimento de cliente',description:`Venda #${String(s.id).slice(-6)}`,amount:n(h.amount),account:'banco',source:'Venda',automatic:true})));return[...inside,...out]}
function all(){return[...derived(),...entries.filter(e=>!e.cancelled)]}
function accountBalance(id){const a=accounts.find(x=>x.id===id),base=n(a?.initial);return all().reduce((t,e)=>{if(e.type==='Transferência')return t+(e.toAccount===id?n(e.amount):0)-(e.account===id?n(e.amount):0);if(e.account!==id)return t;return t+(e.type==='Entrada'?n(e.amount):-n(e.amount))},base)}
function inject(){const old=[...document.querySelectorAll('.module-card')].find(b=>b.textContent.includes('Financeiro'));if(old){const b=old.cloneNode(true);b.classList.remove('locked');b.classList.add('featured');b.dataset.open='financeView';old.replaceWith(b);b.onclick=()=>{openView('financeView');renderFinance()}}
const main=document.querySelector('main');if(!q('#financeView'))main.insertAdjacentHTML('beforeend',`<section id="financeView" class="view"><div class="module-header"><button class="back-button" data-open="homeView">←</button><div><p class="eyebrow">Núcleo 6</p><h1>Financeiro e fluxo de caixa</h1></div></div><section class="capital-summary"><article><span>Saldo disponível</span><strong id="finBalance">R$ 0,00</strong></article><article><span>A receber</span><strong id="finReceivable">R$ 0,00</strong></article><article><span>A pagar</span><strong id="finPayable">R$ 0,00</strong></article><article><span>Resultado realizado</span><strong id="finResult">R$ 0,00</strong></article></section><div class="dual-actions"><button class="primary-button" id="newFinanceEntry">＋ Novo lançamento</button><button class="secondary-button wide" id="newFinanceAccount">＋ Caixa ou banco</button></div><div class="filters"><input id="financeSearch" placeholder="Pesquisar lançamento"><select id="financeType"><option value="all">Todos os tipos</option><option>Entrada</option><option>Saída</option><option>Transferência</option></select></div><div class="list-heading"><h2>Caixa e bancos</h2><span id="financeAccountsCount"></span></div><div id="financeAccounts" class="investor-list"></div><div class="list-heading"><h2>Movimentações financeiras</h2><span id="financeCount"></span></div><div id="financeList" class="purchase-list"></div><div id="financeEmpty" class="empty-state">Nenhuma movimentação financeira.</div></section>`);
document.body.insertAdjacentHTML('beforeend',`<dialog id="financeEntryDialog"><form id="financeEntryForm"><div class="dialog-header"><h2>Novo lançamento financeiro</h2><button type="button" class="close-button" data-fin-close="financeEntryDialog">×</button></div><div class="form-grid"><label>Tipo<select name="type" id="financeEntryType"><option>Entrada</option><option>Saída</option><option>Transferência</option></select></label><label>Data<input name="date" type="date" required></label><label>Categoria<select name="category"><option>Despesa operacional</option><option>Transporte</option><option>Armazenagem</option><option>Impostos</option><option>Comissão</option><option>Combustível</option><option>Manutenção</option><option>Receita diversa</option><option>Ajuste financeiro</option></select></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Conta de origem<select name="account" id="financeAccountSelect" required></select></label><label id="financeDestinationField">Conta de destino<select name="toAccount" id="financeDestinationSelect"></select></label><label>Forma<select name="method"><option>PIX</option><option>Transferência</option><option>Dinheiro</option><option>Boleto</option><option>Cartão</option><option>Outro</option></select></label><label>Status<select name="status"><option>Realizado</option><option>Previsto</option></select></label><label class="full">Descrição<input name="description" required></label><label class="full">Observações<textarea name="notes"></textarea></label></div><button class="primary-button">Salvar lançamento</button></form></dialog><dialog id="financeAccountDialog"><form id="financeAccountForm"><div class="dialog-header"><h2>Novo caixa ou banco</h2><button type="button" class="close-button" data-fin-close="financeAccountDialog">×</button></div><div class="form-grid"><label>Nome<input name="name" required></label><label>Tipo<select name="type"><option>Caixa</option><option>Banco</option></select></label><label>Saldo inicial<input name="initial" type="number" step="0.01" value="0"></label></div><button class="primary-button">Salvar conta</button></form></dialog>`);
q('#financeView .back-button').onclick=()=>openView('homeView');q('#newFinanceEntry').onclick=()=>openEntry();q('#newFinanceAccount').onclick=()=>{q('#financeAccountForm').reset();q('#financeAccountDialog').showModal()};q('#financeSearch').oninput=renderFinance;q('#financeType').onchange=renderFinance;q('#financeEntryType').onchange=toggleDestination;document.querySelectorAll('[data-fin-close]').forEach(b=>b.onclick=()=>q('#'+b.dataset.finClose).close());q('#financeEntryForm').onsubmit=submitEntry;q('#financeAccountForm').onsubmit=submitAccount}
function selects(){const opts=accounts.map(a=>`<option value="${a.id}">${a.name}</option>`).join('');q('#financeAccountSelect').innerHTML=opts;q('#financeDestinationSelect').innerHTML=opts}
function toggleDestination(){q('#financeDestinationField').style.display=q('#financeEntryType').value==='Transferência'?'block':'none';q('#financeDestinationSelect').required=q('#financeEntryType').value==='Transferência'}
function openEntry(){selects();const f=q('#financeEntryForm');f.reset();f.elements.date.value=new Date().toISOString().slice(0,10);toggleDestination();q('#financeEntryDialog').showModal()}
function submitEntry(e){e.preventDefault();const f=new FormData(e.currentTarget),type=f.get('type'),account=f.get('account'),to=f.get('toAccount'),amount=n(f.get('amount'));if(type==='Transferência'&&account===to)return toast('Escolha contas diferentes para a transferência.');if(['Saída','Transferência'].includes(type)&&amount>accountBalance(account))return toast('Saldo insuficiente na conta selecionada.');entries.unshift({id:uid(),type,date:f.get('date'),category:f.get('category'),amount,account,toAccount:type==='Transferência'?to:'',method:f.get('method'),status:f.get('status'),description:f.get('description').trim(),notes:f.get('notes').trim(),createdAt:new Date().toISOString()});save();q('#financeEntryDialog').close();toast('Lançamento financeiro salvo.')}
function submitAccount(e){e.preventDefault();const f=new FormData(e.currentTarget);accounts.push({id:uid(),name:f.get('name').trim(),type:f.get('type'),initial:n(f.get('initial'))});save();q('#financeAccountDialog').close();toast('Conta cadastrada.')}
window.cancelFinanceEntry=id=>{const e=entries.find(x=>x.id===id);if(!e)return;e.cancelled=true;e.cancelledAt=new Date().toISOString();save();toast('Lançamento estornado sem apagar o histórico.')};
function renderFinance(){if(!q('#financeView'))return;const ps=JSON.parse(localStorage.getItem('naturalCastanhasPurchases')||'[]').filter(p=>p.status!=='Cancelada'),ss=JSON.parse(localStorage.getItem('naturalCastanhasSales')||'[]').filter(s=>s.status!=='Cancelada'),payable=ps.reduce((t,p)=>t+Math.max(n(p.total||n(p.quantity)*n(p.unitPrice))-(p.payments||[]).reduce((a,x)=>a+n(x.amount),0),0),0),receivable=ss.reduce((t,s)=>t+Math.max(Math.max(n(s.quantity)*n(s.unitPrice)-n(s.discount),0)-n(s.receivedAmount),0),0),mov=all().filter(e=>e.status!=='Previsto'),income=mov.filter(e=>e.type==='Entrada').reduce((a,e)=>a+n(e.amount),0),expense=mov.filter(e=>e.type==='Saída').reduce((a,e)=>a+n(e.amount),0),balance=accounts.reduce((a,x)=>a+accountBalance(x.id),0);q('#finBalance').textContent=money(balance);q('#finReceivable').textContent=money(receivable);q('#finPayable').textContent=money(payable);q('#finResult').textContent=money(income-expense);q('#metricAvailable').textContent=money(balance);q('#financeAccountsCount').textContent=`${accounts.length} contas`;q('#financeAccounts').innerHTML=accounts.map(a=>`<article class="investor-card"><div class="investor-head"><div><h3>${a.name}</h3><span class="badge">${a.type}</span></div><strong>${money(accountBalance(a.id))}</strong></div><p>Saldo inicial: ${money(a.initial)}</p></article>`).join('');const term=(q('#financeSearch').value||'').toLowerCase(),filter=q('#financeType').value,list=all().filter(e=>(filter==='all'||e.type===filter)&&`${e.description} ${e.category} ${e.source||''}`.toLowerCase().includes(term)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));q('#financeCount').textContent=`${list.length} registros`;q('#financeEmpty').style.display=list.length?'none':'block';q('#financeList').innerHTML=list.map(e=>{const acc=accounts.find(a=>a.id===e.account),dest=accounts.find(a=>a.id===e.toAccount);return`<article class="purchase-item"><div class="purchase-item-top"><div><h3>${e.description}</h3><span class="badge ${e.type==='Saída'?'wait':''}">${e.type}</span></div><strong>${e.type==='Saída'?'- ':e.type==='Entrada'?'+ ':''}${money(e.amount)}</strong></div><p>${date(e.date)} • ${e.category}</p><p>Conta: <strong>${acc?.name||'Conta padrão'}</strong>${dest?` → <strong>${dest.name}</strong>`:''} • ${e.method||'Integração automática'}</p><p>Status: <strong>${e.status||'Realizado'}</strong>${e.automatic?' • Gerado automaticamente':''}</p>${e.notes?`<p>${e.notes}</p>`:''}${!e.automatic?`<div class="item-actions"><button class="delete" onclick="cancelFinanceEntry('${e.id}')">Estornar</button></div>`:''}</article>`}).join('')}
inject();selects();toggleDestination();renderFinance();window.addEventListener('storage',renderFinance);['paymentForm','saleActionForm','capitalForm'].forEach(id=>q('#'+id)?.addEventListener('submit',()=>setTimeout(renderFinance,0)));
const resultsScript=document.createElement('script');resultsScript.src='resultados.js?v=1';resultsScript.defer=true;document.body.appendChild(resultsScript);
})();