const SUPPLIERS_KEY='naturalCastanhasSuppliers';
const PURCHASES_KEY='naturalCastanhasPurchases';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>new Date().toISOString().slice(0,10);
let suppliers=JSON.parse(localStorage.getItem(SUPPLIERS_KEY)||'[]').map(s=>({...s,offers:s.offers||[]}));
let purchases=JSON.parse(localStorage.getItem(PURCHASES_KEY)||'[]');
function toast(m){const e=$('#supplierToast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function save(){localStorage.setItem(SUPPLIERS_KEY,JSON.stringify(suppliers));render()}
function latestOffer(s){return(s.offers||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0]||null}
function purchaseStats(s){const list=purchases.filter(p=>(p.supplier||'').trim().toLowerCase()===s.name.trim().toLowerCase()&&p.status!=='Cancelada');return{count:list.length,quantity:list.reduce((a,p)=>a+Number(p.quantity||0),0),value:list.reduce((a,p)=>a+Number(p.total||0),0)}}
function avgPrice(){const offers=suppliers.map(latestOffer).filter(Boolean);return offers.length?offers.reduce((a,o)=>a+Number(o.price||0),0)/offers.length:0}
function statusClass(s){return s==='Com restrição'?'cancelled':s==='Em observação'?'wait':''}
function renderMetrics(){const offers=suppliers.map(latestOffer).filter(Boolean),average=avgPrice();$('#supplierMetricActive').textContent=suppliers.length;$('#supplierMetricAvailable').textContent=offers.filter(o=>Number(o.quantity)>0).length;$('#supplierMetricVolume').textContent=`${offers.reduce((a,o)=>a+Number(o.quantity||0),0).toLocaleString('pt-BR',{maximumFractionDigits:2})} latas`;$('#supplierMetricPrice').textContent=brl.format(average);$('#supplierMetricDeals').textContent=offers.filter(o=>o.negotiable==='Sim').length;$('#supplierMetricOpportunities').textContent=offers.filter(o=>Number(o.price)<average).length}
function renderSuppliers(){const q=$('#supplierSearch').value.toLowerCase(),f=$('#supplierStatusFilter').value;const list=suppliers.filter(s=>{const o=latestOffer(s);return(`${s.name} ${s.city} ${s.phone} ${s.property}`.toLowerCase().includes(q))&&(f==='all'||s.status===f||(f==='available'&&o&&Number(o.quantity)>0))});$('#supplierCount').textContent=`${list.length} ${list.length===1?'registro':'registros'}`;$('#supplierEmpty').style.display=list.length?'none':'block';$('#supplierList').innerHTML=list.map(s=>{const o=latestOffer(s),p=purchaseStats(s);return`<article class="supplier-card"><div class="supplier-card-top"><div><h3>${s.name}</h3><span class="badge ${statusClass(s.status)}">${s.status}</span><p>${s.type} • ${s.city}/${s.state||'—'}${s.property?` • ${s.property}`:''}</p></div><div class="supplier-score"><strong>${Number(s.reliability||0)}%</strong><span>confiabilidade</span></div></div><div class="supplier-metrics"><div><span>Disponível agora</span><strong>${o?`${Number(o.quantity).toLocaleString('pt-BR')} latas`:'Não informado'}</strong></div><div><span>Preço atual</span><strong>${o?brl.format(o.price):'Não informado'}</strong></div><div><span>Qualidade média</span><strong>${Number(s.quality||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}/10</strong></div><div><span>Distância</span><strong>${s.distance?`${Number(s.distance).toLocaleString('pt-BR')} km`:'Não informada'}</strong></div><div><span>Compras realizadas</span><strong>${p.count}</strong></div><div><span>Volume comprado</span><strong>${p.quantity.toLocaleString('pt-BR')} latas</strong></div></div>${s.phone?`<p>WhatsApp: <strong>${s.phone}</strong></p>`:''}${s.notes?`<p>${s.notes}</p>`:''}<div class="item-actions"><button onclick="editSupplier('${s.id}')">Editar</button><button onclick="offerFor('${s.id}')">Disponibilidade</button><button onclick="startPurchase('${s.id}')">Iniciar compra</button><button class="danger-link" onclick="removeSupplier('${s.id}')">Excluir</button></div></article>`}).join('')}
function renderOpportunities(){const average=avgPrice();const items=suppliers.map(s=>({s,o:latestOffer(s)})).filter(x=>x.o&&Number(x.o.quantity)>0&&average>0&&Number(x.o.price)<average).sort((a,b)=>Number(a.o.price)-Number(b.o.price));$('#opportunityEmpty').style.display=items.length?'none':'block';$('#opportunityList').innerHTML=items.map(({s,o})=>{const pct=((average-Number(o.price))/average)*100;return`<article class="opportunity-card"><h3>${s.name}</h3><p class="opportunity-highlight"><strong>${Number(o.quantity).toLocaleString('pt-BR')} latas</strong> por <strong>${brl.format(o.price)}</strong></p><p>Oferta ${pct.toLocaleString('pt-BR',{maximumFractionDigits:1})}% abaixo da média atual de ${brl.format(average)}.</p><p>${s.city}/${s.state||'—'} • ${s.distance?`${s.distance} km`: 'distância não informada'} • qualidade ${Number(s.quality||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}/10</p><div class="item-actions"><button onclick="startPurchase('${s.id}')">Iniciar negociação</button><button onclick="offerFor('${s.id}')">Atualizar oferta</button></div></article>`}).join('')}
function renderCompare(){const selected=$$('.compare-check:checked').map(x=>suppliers.find(s=>s.id===x.value)).filter(Boolean);$('#compareSelector').innerHTML=suppliers.map(s=>`<label class="compare-option"><input class="compare-check" type="checkbox" value="${s.id}" ${selected.some(x=>x.id===s.id)?'checked':''}><span><strong>${s.name}</strong><br>${s.city}/${s.state||'—'}</span></label>`).join('')||'<div class="empty-state"><p>Cadastre fornecedores para comparar.</p></div>';$$('.compare-check').forEach(c=>c.onchange=()=>{const checked=$$('.compare-check:checked');if(checked.length>3){c.checked=false;toast('Selecione no máximo três fornecedores.')}renderCompareResult()});renderCompareResult()}
function renderCompareResult(){const list=$$('.compare-check:checked').map(x=>suppliers.find(s=>s.id===x.value)).filter(Boolean);if(list.length<2){$('#compareResult').innerHTML='<div class="empty-state"><span>⚖️</span><p>Selecione pelo menos dois fornecedores.</p></div>';return}const offers=list.map(latestOffer),prices=offers.map(o=>o?Number(o.price):Infinity),qualities=list.map(s=>Number(s.quality||0)),distances=list.map(s=>s.distance?Number(s.distance):Infinity),reliabilities=list.map(s=>Number(s.reliability||0));const row=(label,vals,best,type)=>`<tr><td>${label}</td>${vals.map((v,i)=>`<td class="${i===best?'best':''}">${type==='money'?(Number.isFinite(v)?brl.format(v):'—'):type==='percent'?`${v}%`:type==='distance'?(Number.isFinite(v)?`${v} km`:'—'):v}</td>`).join('')}</tr>`;$('#compareResult').innerHTML=`<table class="compare-table"><thead><tr><th>Critério</th>${list.map(s=>`<th>${s.name}</th>`).join('')}</tr></thead><tbody>${row('Preço por lata',prices,prices.indexOf(Math.min(...prices)),'money')}${row('Quantidade disponível',offers.map(o=>o?Number(o.quantity):0),offers.map(o=>o?Number(o.quantity):0).indexOf(Math.max(...offers.map(o=>o?Number(o.quantity):0))),'number')}${row('Qualidade',qualities,qualities.indexOf(Math.max(...qualities)),'number')}${row('Confiabilidade',reliabilities,reliabilities.indexOf(Math.max(...reliabilities)),'percent')}${row('Distância',distances,distances.indexOf(Math.min(...distances)),'distance')}</tbody></table>`}
function fillSupplierSelect(){const s=$('#availabilitySupplier');s.innerHTML='<option value="">Selecione</option>'+suppliers.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
function openSupplier(id=''){const f=$('#supplierForm');f.reset();f.elements.supplierId.value=id;if(id){const s=suppliers.find(x=>x.id===id);Object.keys(s).forEach(k=>{if(f.elements[k]&&typeof s[k]!=='object')f.elements[k].value=s[k]??''});$('#supplierDialogTitle').textContent='Editar fornecedor'}else{$('#supplierDialogTitle').textContent='Novo fornecedor';f.elements.state.value='RO';f.elements.quality.value='8';f.elements.reliability.value='80'}$('#supplierDialog').showModal()}
function openAvailability(id=''){if(!suppliers.length)return toast('Cadastre primeiro um fornecedor.');const f=$('#availabilityForm');f.reset();fillSupplierSelect();f.elements.date.value=today();if(id)f.elements.supplierId.value=id;$('#availabilityDialog').showModal()}
function render(){renderMetrics();renderSuppliers();renderOpportunities();renderCompare();fillSupplierSelect()}
$('#newSupplierButton').onclick=()=>openSupplier();$('#newAvailabilityButton').onclick=()=>openAvailability();$('#supplierSearch').oninput=renderSuppliers;$('#supplierStatusFilter').onchange=renderSuppliers;$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());$$('.supplier-tools button').forEach(b=>b.onclick=()=>{$$('.supplier-tools button').forEach(x=>x.classList.toggle('active',x===b));$$('.supplier-panel').forEach(p=>p.classList.toggle('active',p.id===`${b.dataset.tab}Panel`))});
$('#supplierForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('supplierId'),record={id:id||String(Date.now()),name:f.get('name').trim(),type:f.get('type'),document:f.get('document').trim(),phone:f.get('phone').trim(),property:f.get('property').trim(),city:f.get('city').trim(),state:f.get('state').trim().toUpperCase(),distance:Number(f.get('distance')||0),payment:f.get('payment'),status:f.get('status'),quality:Number(f.get('quality')||0),reliability:Number(f.get('reliability')||0),notes:f.get('notes').trim(),offers:id?(suppliers.find(s=>s.id===id)?.offers||[]):[]};if(id)suppliers=suppliers.map(s=>s.id===id?record:s);else suppliers.unshift(record);save();$('#supplierDialog').close();toast(id?'Fornecedor atualizado.':'Fornecedor cadastrado.')};
$('#availabilityForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),s=suppliers.find(x=>x.id===f.get('supplierId'));s.offers.unshift({id:String(Date.now()),date:f.get('date'),quantity:Number(f.get('quantity')),price:Number(f.get('price')),validUntil:f.get('validUntil'),deliveryDays:Number(f.get('deliveryDays')||0),condition:f.get('condition'),negotiable:f.get('negotiable'),notes:f.get('notes').trim()});save();$('#availabilityDialog').close();toast('Disponibilidade registrada.')};
window.editSupplier=id=>openSupplier(id);window.offerFor=id=>openAvailability(id);window.removeSupplier=id=>{const s=suppliers.find(x=>x.id===id);if(confirm(`Excluir o fornecedor ${s.name}?`)){suppliers=suppliers.filter(x=>x.id!==id);save();toast('Fornecedor excluído.')}};window.startPurchase=id=>{const s=suppliers.find(x=>x.id===id),o=latestOffer(s);localStorage.setItem('naturalCastanhasPurchaseDraft',JSON.stringify({supplier:s.name,quantity:o?.quantity||'',unitPrice:o?.price||''}));location.href='./?nova-compra=1'};
render();