(()=>{
const LOTS_KEY='naturalCastanhasLots';
const DEPOSITS_KEY='naturalCastanhasDeposits';
const STOCK_MOVES_KEY='naturalCastanhasStockMovements';
const RESERVES_KEY='naturalCastanhasStockReserves';
const qs=s=>document.querySelector(s);
const qsa=s=>[...document.querySelectorAll(s)];
const fmt=n=>Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const dateBR=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const nowId=()=>String(Date.now());
const today4=()=>new Date().toISOString().slice(0,10);
let lots=JSON.parse(localStorage.getItem(LOTS_KEY)||'[]');
let deposits=JSON.parse(localStorage.getItem(DEPOSITS_KEY)||'[]');
let stockMoves=JSON.parse(localStorage.getItem(STOCK_MOVES_KEY)||'[]');
let reserves=JSON.parse(localStorage.getItem(RESERVES_KEY)||'[]');
const save4=()=>{localStorage.setItem(LOTS_KEY,JSON.stringify(lots));localStorage.setItem(DEPOSITS_KEY,JSON.stringify(deposits));localStorage.setItem(STOCK_MOVES_KEY,JSON.stringify(stockMoves));localStorage.setItem(RESERVES_KEY,JSON.stringify(reserves));renderStock()};
const showToast4=m=>typeof toast==='function'?toast(m):alert(m);
const activeReserve=l=>reserves.filter(r=>r.lotId===l.id&&r.status==='Ativa').reduce((a,r)=>a+Number(r.quantity||0),0);
const lotAvailable=l=>Math.max(Number(l.currentWeight||0)-activeReserve(l),0);
const depositName=id=>deposits.find(d=>d.id===id)?.name||'Não informado';
const qualityClass=q=>q==='Premium'?'premium':q==='Tipo A'?'good':q==='Industrial'?'industrial':'';

function injectStyle(){const s=document.createElement('style');s.textContent=`
.stock-summary{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:18px}.stock-summary article{background:#fff;border:1px solid var(--line);border-radius:17px;padding:14px;box-shadow:0 7px 20px rgba(30,50,35,.06)}.stock-summary span{display:block;font-size:11px;color:var(--muted)}.stock-summary strong{display:block;margin-top:6px;font-size:18px;color:var(--green)}.stock-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:14px 0}.stock-actions button{margin:0}.stock-tabs{display:flex;gap:8px;overflow-x:auto;padding:3px 0 8px;scrollbar-width:none}.stock-tabs::-webkit-scrollbar{display:none}.stock-tabs button{white-space:nowrap;border:1px solid var(--line);background:#fff;border-radius:999px;padding:9px 13px;font-weight:800;color:var(--muted)}.stock-tabs button.active{background:var(--green);color:#fff;border-color:var(--green)}.stock-panel{display:none}.stock-panel.active{display:block}.lot-card,.deposit-card,.movement-card,.reserve-card{background:#fff;border:1px solid var(--line);border-radius:17px;padding:15px;margin-bottom:11px;box-shadow:0 6px 18px rgba(0,0,0,.04)}.lot-top,.stock-row{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.lot-card h3,.deposit-card h3,.movement-card h3,.reserve-card h3{font-size:15px;margin-bottom:5px}.lot-card p,.deposit-card p,.movement-card p,.reserve-card p{font-size:12px;color:var(--muted);margin:5px 0}.lot-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.lot-metrics div{background:#f4f7f3;border-radius:11px;padding:9px}.lot-metrics span{display:block;font-size:10px;color:var(--muted)}.lot-metrics strong{font-size:12px}.badge.premium{background:#fff4cc;color:#8b6700}.badge.good{background:#e9f7eb;color:#286b32}.badge.industrial{background:#edf0f3;color:#59636d}.stock-empty{text-align:center;color:var(--muted);padding:34px 12px}.trace-line{border-left:3px solid #dbe8dc;margin:12px 0 0 7px;padding-left:15px}.trace-event{position:relative;margin-bottom:13px}.trace-event:before{content:'';position:absolute;width:9px;height:9px;border-radius:50%;background:var(--green);left:-21px;top:4px}.trace-event strong{font-size:12px}.trace-event p{font-size:11px;margin:3px 0}.capacity-bar{height:8px;border-radius:999px;background:#e8ece7;overflow:hidden;margin-top:9px}.capacity-bar i{display:block;height:100%;background:var(--green);border-radius:999px}.stock-alert{background:#fff4df;border:1px solid #f1d9a9;border-radius:14px;padding:12px;margin:12px 0;font-size:12px;color:#7d5708}.compact-select{margin-top:12px}@media(max-width:420px){.stock-summary{grid-template-columns:repeat(2,1fr)}.stock-actions{grid-template-columns:1fr 1fr}.lot-metrics{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)}

function injectView(){const main=qs('main.app-shell');if(!main||qs('#stockView'))return;main.insertAdjacentHTML('beforeend',`
<section id="stockView" class="view">
 <div class="module-header"><button class="back-button" data-open-stock="homeView">←</button><div><p class="eyebrow">Núcleo 4</p><h1>Estoque, lotes e rastreabilidade</h1></div></div>
 <section class="stock-summary">
  <article><span>Estoque físico</span><strong id="stockPhysical">0 latas</strong></article>
  <article><span>Disponível</span><strong id="stockAvailable">0 latas</strong></article>
  <article><span>Lotes ativos</span><strong id="stockLots">0</strong></article>
  <article><span>Reservado</span><strong id="stockReserved">0 latas</strong></article>
  <article><span>Depósitos</span><strong id="stockDeposits">0</strong></article>
  <article><span>Perdas registradas</span><strong id="stockLosses">0 latas</strong></article>
 </section>
 <div id="stockAlerts"></div>
 <div class="stock-actions"><button class="primary-button" id="newLotButton">＋ Novo lote</button><button class="secondary-button wide" id="newDepositButton">＋ Depósito</button></div>
 <div class="stock-tabs"><button class="active" data-stock-tab="lotsPanel">Lotes</button><button data-stock-tab="depositsPanel">Depósitos</button><button data-stock-tab="reservesPanel">Reservas</button><button data-stock-tab="movesPanel">Movimentações</button></div>
 <section id="lotsPanel" class="stock-panel active"><div class="filters"><input id="lotSearch" type="search" placeholder="Pesquisar lote, fornecedor ou depósito"><select id="lotStatus"><option value="all">Todos os status</option><option>Disponível</option><option>Reservado</option><option>Bloqueado</option><option>Em transporte</option><option>Encerrado</option></select></div><div class="list-heading"><h2>Lotes</h2><span id="lotCount">0 registros</span></div><div id="lotsList"></div></section>
 <section id="depositsPanel" class="stock-panel"><div class="list-heading"><h2>Depósitos</h2><span id="depositCount">0 cadastrados</span></div><div id="depositsList"></div></section>
 <section id="reservesPanel" class="stock-panel"><div class="list-heading"><h2>Reservas de estoque</h2><span id="reserveCount">0 ativas</span></div><div id="reservesList"></div></section>
 <section id="movesPanel" class="stock-panel"><div class="list-heading"><h2>Histórico de movimentações</h2><span id="moveCount">0 registros</span></div><div id="movesList"></div></section>
</section>`);
 document.body.insertAdjacentHTML('beforeend',`
<dialog id="depositDialog"><form id="depositForm"><div class="dialog-header"><div><p class="eyebrow">Armazenagem</p><h2>Novo depósito</h2></div><button type="button" class="close-button" data-close4="depositDialog">×</button></div><div class="form-grid"><label>Nome<input name="name" required></label><label>Código<input name="code" required></label><label>Município<input name="city" required></label><label>Estado<input name="state" value="RO" maxlength="2" required></label><label>Responsável<input name="manager"></label><label>Capacidade máxima (latas)<input name="capacity" type="number" min="0" step="0.01" required></label><label class="full">Endereço<input name="address"></label><label class="full">Observações<textarea name="notes" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="secondary-button" data-close4="depositDialog">Cancelar</button><button class="primary-button" type="submit">Salvar depósito</button></div></form></dialog>
<dialog id="lotDialog"><form id="lotForm"><div class="dialog-header"><div><p class="eyebrow">Formação de lote</p><h2>Novo lote</h2></div><button type="button" class="close-button" data-close4="lotDialog">×</button></div><div class="form-grid"><label>Data de criação<input name="date" type="date" required></label><label>Depósito<select name="depositId" id="lotDeposit" required></select></label><label>Fornecedor<input name="supplier" required></label><label>Compra de origem<input name="purchaseId" placeholder="Número da compra"></label><label>Peso inicial (latas)<input name="weight" type="number" min="0.01" step="0.01" required></label><label>Qualidade<select name="quality"><option>Premium</option><option>Tipo A</option><option>Tipo B</option><option>Tipo C</option><option>Industrial</option></select></label><label>Umidade (%)<input name="moisture" type="number" min="0" step="0.01"></label><label>Impurezas (%)<input name="impurities" type="number" min="0" step="0.01"></label><label>Status<select name="status"><option>Disponível</option><option>Bloqueado</option><option>Em análise</option></select></label><label>Origem/município<input name="origin"></label><label class="full">Observações<textarea name="notes" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="secondary-button" data-close4="lotDialog">Cancelar</button><button class="primary-button" type="submit">Criar lote</button></div></form></dialog>
<dialog id="stockActionDialog"><form id="stockActionForm"><input name="lotId" type="hidden"><div class="dialog-header"><div><p class="eyebrow">Movimentação</p><h2 id="stockActionTitle">Registrar operação</h2></div><button type="button" class="close-button" data-close4="stockActionDialog">×</button></div><div class="form-grid"><label>Operação<select name="type" id="stockActionType"><option>Transferência</option><option>Reserva</option><option>Perda</option><option>Ajuste positivo</option><option>Ajuste negativo</option><option>Inventário</option><option>Bloqueio</option><option>Desbloqueio</option></select></label><label>Data<input name="date" type="date" required></label><label>Quantidade (latas)<input name="quantity" type="number" min="0" step="0.01"></label><label id="destinationLabel">Depósito de destino<select name="destinationId" id="stockDestination"></select></label><label id="clientLabel">Cliente/pedido<input name="client"></label><label class="full">Motivo ou observações<textarea name="notes" rows="3" required></textarea></label></div><div class="dialog-actions"><button type="button" class="secondary-button" data-close4="stockActionDialog">Cancelar</button><button class="primary-button" type="submit">Registrar</button></div></form></dialog>`);
}

function activateCard(){const card=qsa('.module-card').find(c=>c.querySelector('strong')?.textContent.trim()==='Estoque');if(!card)return;card.classList.remove('locked');card.classList.add('featured');card.dataset.open='stockView';if(!card.querySelector('.module-number'))card.insertAdjacentHTML('afterbegin','<span class="module-number">4</span>');card.querySelector('strong').textContent='Estoque, lotes e rastreabilidade';card.querySelector('small').textContent='Recebimento, armazenagem e movimentações';card.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openView('stockView');renderStock()},{capture:true})}
function fillDeposits(){const options='<option value="">Selecione</option>'+deposits.map(d=>`<option value="${d.id}">${d.name} — ${d.city}</option>`).join('');qs('#lotDeposit').innerHTML=options;qs('#stockDestination').innerHTML=options}
function openD(id){const d=qs('#'+id);d.showModal()}
function openAction(lotId,type='Transferência'){const f=qs('#stockActionForm');f.reset();f.elements.lotId.value=lotId;f.elements.date.value=today4();f.elements.type.value=type;toggleActionFields();qs('#stockActionTitle').textContent=`${type} do lote`;openD('stockActionDialog')}
function toggleActionFields(){const t=qs('#stockActionType').value;qs('#destinationLabel').style.display=t==='Transferência'?'block':'none';qs('#clientLabel').style.display=t==='Reserva'?'block':'none'}

function renderStock(){if(!qs('#stockView'))return;fillDeposits();const physical=lots.filter(l=>l.status!=='Encerrado').reduce((a,l)=>a+Number(l.currentWeight||0),0);const reserved=reserves.filter(r=>r.status==='Ativa').reduce((a,r)=>a+Number(r.quantity||0),0);const available=lots.filter(l=>!['Encerrado','Bloqueado','Em transporte'].includes(l.status)).reduce((a,l)=>a+lotAvailable(l),0);const losses=stockMoves.filter(m=>m.type==='Perda').reduce((a,m)=>a+Number(m.quantity||0),0);qs('#stockPhysical').textContent=`${fmt(physical)} latas`;qs('#stockAvailable').textContent=`${fmt(available)} latas`;qs('#stockLots').textContent=lots.filter(l=>l.status!=='Encerrado').length;qs('#stockReserved').textContent=`${fmt(reserved)} latas`;qs('#stockDeposits').textContent=deposits.length;qs('#stockLosses').textContent=`${fmt(losses)} latas`;const alerts=[];deposits.forEach(d=>{const used=lots.filter(l=>l.depositId===d.id&&l.status!=='Encerrado').reduce((a,l)=>a+Number(l.currentWeight||0),0);if(Number(d.capacity)>0&&used/Number(d.capacity)>=.9)alerts.push(`${d.name} está com ${Math.round(used/Number(d.capacity)*100)}% da capacidade ocupada.`)});lots.filter(l=>l.status==='Bloqueado').forEach(l=>alerts.push(`O lote ${l.code} está bloqueado.`));qs('#stockAlerts').innerHTML=alerts.length?`<div class="stock-alert"><strong>Atenção:</strong><br>${alerts.join('<br>')}</div>`:'';
 const q=(qs('#lotSearch')?.value||'').toLowerCase(),st=qs('#lotStatus')?.value||'all';const filtered=lots.filter(l=>(st==='all'||l.status===st)&&`${l.code} ${l.supplier} ${depositName(l.depositId)}`.toLowerCase().includes(q));qs('#lotCount').textContent=`${filtered.length} ${filtered.length===1?'registro':'registros'}`;qs('#lotsList').innerHTML=filtered.length?filtered.map(l=>{const r=activeReserve(l),trace=stockMoves.filter(m=>m.lotId===l.id);return `<article class="lot-card"><div class="lot-top"><div><h3>${l.code}</h3><span class="badge ${qualityClass(l.quality)}">${l.quality}</span> <span class="badge">${l.status}</span></div><strong>${fmt(l.currentWeight)} latas</strong></div><p>Fornecedor: <strong>${l.supplier}</strong>${l.origin?` • Origem: ${l.origin}`:''}</p><p>Depósito: <strong>${depositName(l.depositId)}</strong> • Criado em ${dateBR(l.date)}</p><div class="lot-metrics"><div><span>Peso inicial</span><strong>${fmt(l.initialWeight)}</strong></div><div><span>Reservado</span><strong>${fmt(r)}</strong></div><div><span>Disponível</span><strong>${fmt(lotAvailable(l))}</strong></div></div><div class="item-actions"><button onclick="window.stockAction('${l.id}','Transferência')">Transferir</button><button onclick="window.stockAction('${l.id}','Reserva')">Reservar</button><button onclick="window.stockAction('${l.id}','Perda')">Perda/ajuste</button><button onclick="window.stockAction('${l.id}','Inventário')">Inventário</button></div><details><summary>Rastreabilidade completa</summary><div class="trace-line"><div class="trace-event"><strong>Formação do lote</strong><p>${dateBR(l.date)} — ${fmt(l.initialWeight)} latas recebidas de ${l.supplier}.</p></div>${trace.map(m=>`<div class="trace-event"><strong>${m.type}</strong><p>${dateBR(m.date)} — ${fmt(m.quantity)} latas. ${m.notes||''}${m.destinationId?` Destino: ${depositName(m.destinationId)}.`:''}</p></div>`).join('')||''}</div></details></article>`}).join(''):'<div class="stock-empty">Nenhum lote encontrado.</div>';
 qs('#depositCount').textContent=`${deposits.length} cadastrados`;qs('#depositsList').innerHTML=deposits.length?deposits.map(d=>{const used=lots.filter(l=>l.depositId===d.id&&l.status!=='Encerrado').reduce((a,l)=>a+Number(l.currentWeight||0),0),pct=Number(d.capacity)>0?Math.min(used/Number(d.capacity)*100,100):0;return `<article class="deposit-card"><div class="stock-row"><div><h3>${d.name}</h3><span class="badge">${d.code}</span></div><strong>${Math.round(pct)}%</strong></div><p>${d.city}/${d.state}${d.manager?` • Responsável: ${d.manager}`:''}</p><p>Ocupação: <strong>${fmt(used)} de ${fmt(d.capacity)} latas</strong></p><div class="capacity-bar"><i style="width:${pct}%"></i></div></article>`}).join(''):'<div class="stock-empty">Nenhum depósito cadastrado.</div>';
 const active=reserves.filter(r=>r.status==='Ativa');qs('#reserveCount').textContent=`${active.length} ativas`;qs('#reservesList').innerHTML=reserves.length?reserves.map(r=>{const l=lots.find(x=>x.id===r.lotId);return `<article class="reserve-card"><div class="stock-row"><div><h3>${r.client||'Reserva sem cliente'}</h3><span class="badge">${r.status}</span></div><strong>${fmt(r.quantity)} latas</strong></div><p>Lote: <strong>${l?.code||'Não localizado'}</strong> • ${dateBR(r.date)}</p>${r.status==='Ativa'?`<div class="item-actions"><button class="delete" onclick="window.releaseReserve('${r.id}')">Liberar reserva</button></div>`:''}</article>`}).join(''):'<div class="stock-empty">Nenhuma reserva registrada.</div>';
 qs('#moveCount').textContent=`${stockMoves.length} registros`;qs('#movesList').innerHTML=stockMoves.length?stockMoves.map(m=>{const l=lots.find(x=>x.id===m.lotId);return `<article class="movement-card"><div class="stock-row"><div><h3>${m.type}</h3><span class="badge">${dateBR(m.date)}</span></div><strong>${fmt(m.quantity)} latas</strong></div><p>Lote: <strong>${l?.code||'Não localizado'}</strong>${m.destinationId?` • Destino: ${depositName(m.destinationId)}`:''}</p><p>${m.notes||'Sem observações.'}</p></article>`}).join(''):'<div class="stock-empty">Nenhuma movimentação registrada.</div>';
 const homeMetric=qs('#metricStock');if(homeMetric)homeMetric.textContent=`${fmt(physical)} latas`;
}

function bind(){qsa('[data-close4]').forEach(b=>b.onclick=()=>qs('#'+b.dataset.close4).close());qsa('[data-open-stock]').forEach(b=>b.onclick=()=>openView(b.dataset.openStock));qsa('[data-stock-tab]').forEach(b=>b.onclick=()=>{qsa('[data-stock-tab]').forEach(x=>x.classList.toggle('active',x===b));qsa('.stock-panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.stockTab))});qs('#newDepositButton').onclick=()=>{qs('#depositForm').reset();openD('depositDialog')};qs('#newLotButton').onclick=()=>{if(!deposits.length)return showToast4('Cadastre um depósito antes de criar o lote.');qs('#lotForm').reset();qs('#lotForm').elements.date.value=today4();fillDeposits();openD('lotDialog')};qs('#lotSearch').oninput=renderStock;qs('#lotStatus').onchange=renderStock;qs('#stockActionType').onchange=toggleActionFields;
 qs('#depositForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);deposits.unshift({id:nowId(),name:f.get('name').trim(),code:f.get('code').trim(),city:f.get('city').trim(),state:f.get('state').trim().toUpperCase(),manager:f.get('manager').trim(),capacity:Number(f.get('capacity')),address:f.get('address').trim(),notes:f.get('notes').trim()});save4();qs('#depositDialog').close();showToast4('Depósito cadastrado com sucesso.')};
 qs('#lotForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),weight=Number(f.get('weight')),year=new Date(f.get('date')+'T12:00:00').getFullYear(),seq=String(lots.length+1).padStart(6,'0');lots.unshift({id:nowId(),code:`NC-${year}-${seq}`,date:f.get('date'),depositId:f.get('depositId'),supplier:f.get('supplier').trim(),purchaseId:f.get('purchaseId').trim(),initialWeight:weight,currentWeight:weight,quality:f.get('quality'),moisture:Number(f.get('moisture')||0),impurities:Number(f.get('impurities')||0),status:f.get('status'),origin:f.get('origin').trim(),notes:f.get('notes').trim()});stockMoves.unshift({id:nowId()+'m',lotId:lots[0].id,type:'Recebimento e formação do lote',date:f.get('date'),quantity:weight,notes:`Lote formado a partir da compra ${f.get('purchaseId')||'não informada'}.`});save4();qs('#lotDialog').close();showToast4('Lote criado e rastreabilidade iniciada.')};
 qs('#stockActionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),l=lots.find(x=>x.id===f.get('lotId')),type=f.get('type'),qty=Number(f.get('quantity')||0),notes=f.get('notes').trim(),destinationId=f.get('destinationId');if(!l)return;if(['Perda','Ajuste negativo','Reserva','Transferência'].includes(type)&&qty<=0)return showToast4('Informe uma quantidade válida.');if(['Perda','Ajuste negativo','Reserva'].includes(type)&&qty>lotAvailable(l))return showToast4('Quantidade maior que o saldo disponível do lote.');if(type==='Transferência'){if(!destinationId||destinationId===l.depositId)return showToast4('Selecione um depósito de destino diferente.');l.depositId=destinationId;l.status='Disponível'}else if(type==='Reserva'){reserves.unshift({id:nowId(),lotId:l.id,date:f.get('date'),quantity:qty,client:f.get('client').trim(),notes,status:'Ativa'});l.status=lotAvailable(l)-qty<=0?'Reservado':l.status}else if(type==='Perda'||type==='Ajuste negativo'){l.currentWeight=Math.max(Number(l.currentWeight)-qty,0);if(l.currentWeight===0)l.status='Encerrado'}else if(type==='Ajuste positivo'){l.currentWeight=Number(l.currentWeight)+qty}else if(type==='Inventário'){const counted=qty,diff=counted-Number(l.currentWeight);l.currentWeight=counted;stockMoves.unshift({id:nowId()+'i',lotId:l.id,type:diff>=0?'Ajuste positivo de inventário':'Ajuste negativo de inventário',date:f.get('date'),quantity:Math.abs(diff),notes:`${notes} Saldo anterior: ${fmt(counted-diff)}; saldo contado: ${fmt(counted)}.`});save4();qs('#stockActionDialog').close();return showToast4('Inventário registrado e saldo ajustado.')}else if(type==='Bloqueio')l.status='Bloqueado';else if(type==='Desbloqueio')l.status='Disponível';stockMoves.unshift({id:nowId(),lotId:l.id,type,date:f.get('date'),quantity:qty,destinationId:type==='Transferência'?destinationId:'',notes});save4();qs('#stockActionDialog').close();showToast4('Movimentação registrada no histórico.')};
}
window.stockAction=openAction;window.releaseReserve=id=>{const r=reserves.find(x=>x.id===id);if(!r)return;r.status='Liberada';r.releasedAt=today4();const l=lots.find(x=>x.id===r.lotId);if(l&&l.status==='Reservado')l.status='Disponível';stockMoves.unshift({id:nowId(),lotId:r.lotId,type:'Liberação de reserva',date:today4(),quantity:r.quantity,notes:`Reserva de ${r.client||'cliente não informado'} liberada.`});save4();showToast4('Reserva liberada e lote atualizado.')};
function init(){injectStyle();injectView();activateCard();bind();renderStock()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();