(()=>{
const KEYS={purchases:'naturalCastanhasPurchases',investors:'naturalCastanhasInvestors',capital:'naturalCastanhasCapital',clients:'naturalCastanhasClients',sales:'naturalCastanhasSales'};
const $=s=>document.querySelector(s),num=v=>Number(v||0),money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(num(v)),pct=v=>`${num(v).toFixed(1)}%`,date=v=>v?new Date(v+'T12:00:00'):null;
const load=k=>{try{return JSON.parse(localStorage.getItem(KEYS[k])||'[]')}catch{return[]}};
const css=`
.reports-toolbar{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.reports-toolbar label{font-size:12px;color:#667085}.reports-toolbar input,.reports-toolbar select{width:100%;margin-top:5px}.report-kpis{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.report-kpi,.report-panel{background:#fff;border:1px solid #e7ece7;border-radius:16px;padding:14px;box-shadow:0 5px 16px rgba(31,72,38,.06)}.report-kpi span{display:block;color:#667085;font-size:12px;margin-bottom:6px}.report-kpi strong{font-size:18px;color:#173d21}.report-section{margin-top:18px}.report-section h2{font-size:18px;margin:0 0 10px}.report-grid{display:grid;grid-template-columns:1fr;gap:12px}.report-row{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid #edf1ed}.report-row:last-child{border-bottom:0}.report-row span{color:#667085}.report-row strong{text-align:right}.report-bar{height:8px;background:#edf2ed;border-radius:999px;overflow:hidden;margin-top:6px}.report-bar i{display:block;height:100%;background:#2f6f38;border-radius:999px}.report-alert{padding:11px 12px;border-radius:12px;background:#fff7e6;border:1px solid #f3d7a0;margin-bottom:8px;font-size:13px}.report-alert.good{background:#edf8ef;border-color:#bddfc3}.report-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.report-actions button{border:0;border-radius:12px;padding:11px 14px;font-weight:700;background:#24552a;color:#fff}.report-empty{color:#667085;text-align:center;padding:20px}.rank-number{display:inline-grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#edf4ee;color:#24552a;font-weight:800;margin-right:8px}@media(min-width:700px){.report-kpis{grid-template-columns:repeat(4,1fr)}.report-grid{grid-template-columns:repeat(2,1fr)}}@media print{.topbar,.bottom-nav,footer,.module-header button,.report-actions,.reports-toolbar{display:none!important}.view{display:none!important}#reportsView{display:block!important}.app-shell{max-width:none}.report-panel,.report-kpi{box-shadow:none}}
`;
function install(){
 if($('#reportsView'))return;
 const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
 const grid=$('.module-grid');if(grid){const b=document.createElement('button');b.className='module-card featured';b.dataset.open='reportsView';b.innerHTML='<span class="module-number">9</span><span class="module-icon">📊</span><strong>Relatórios</strong><small>Indicadores e inteligência</small>';grid.appendChild(b);b.addEventListener('click',()=>{openView('reportsView');renderReports()})}
 const main=$('.app-shell');const view=document.createElement('section');view.id='reportsView';view.className='view';view.innerHTML=`<div class="module-header"><button class="back-button" data-open="homeView">←</button><div><p class="eyebrow">Núcleo 9</p><h1>Relatórios e inteligência</h1></div></div><div class="reports-toolbar"><label>Período<select id="reportPeriod"><option value="all">Todo o período</option><option value="month">Este mês</option><option value="quarter">Últimos 3 meses</option><option value="year">Este ano</option><option value="custom">Personalizado</option></select></label><label>Até<input id="reportEnd" type="date"></label><label>De<input id="reportStart" type="date"></label><label>Visão<select id="reportView"><option value="general">Geral</option><option value="financial">Financeira</option><option value="commercial">Comercial</option><option value="stock">Estoque</option></select></label></div><div class="report-actions"><button id="refreshReports">Atualizar</button><button id="printReports">Exportar / imprimir</button></div><section id="reportContent"></section>`;main.appendChild(view);
 view.querySelector('[data-open="homeView"]').onclick=()=>openView('homeView');
 $('#reportEnd').value=new Date().toISOString().slice(0,10);$('#reportStart').value='';
 $('#reportPeriod').onchange=setPeriod;$('#reportStart').onchange=renderReports;$('#reportEnd').onchange=renderReports;$('#reportView').onchange=renderReports;$('#refreshReports').onclick=renderReports;$('#printReports').onclick=()=>window.print();
}
function setPeriod(){const type=$('#reportPeriod').value,end=new Date(),start=new Date(end);if(type==='month')start.setDate(1);else if(type==='quarter')start.setMonth(start.getMonth()-3);else if(type==='year')start.setMonth(0,1);else if(type==='all'){$('#reportStart').value='';renderReports();return}$('#reportStart').value=start.toISOString().slice(0,10);$('#reportEnd').value=end.toISOString().slice(0,10);renderReports()}
function inRange(v){if(!v)return true;const d=date(v),s=$('#reportStart')?.value?date($('#reportStart').value):null,e=$('#reportEnd')?.value?date($('#reportEnd').value):null;return(!s||d>=s)&&(!e||d<=e)}
function purchaseTotal(p){return num(p.total)||num(p.quantity)*num(p.unitPrice)}
function receipts(p){return(p.receipts||[]).reduce((a,r)=>a+num(r.approved),0)}
function payments(p){return(p.payments||[]).reduce((a,r)=>a+num(r.amount),0)}
function saleGross(s){return Math.max(num(s.quantity)*num(s.unitPrice)-num(s.discount),0)}
function data(){const purchases=load('purchases').filter(p=>p.status!=='Cancelada'&&inRange(p.date)),sales=load('sales').filter(s=>s.status!=='Cancelada'&&inRange(s.date)),capital=load('capital').filter(e=>!e.reversed&&inRange(e.date)),clients=load('clients'),investors=load('investors');const purchasedQty=purchases.reduce((a,p)=>a+num(p.quantity),0),purchaseCost=purchases.reduce((a,p)=>a+purchaseTotal(p),0),approved=purchases.reduce((a,p)=>a+receipts(p),0),paidPurchases=purchases.reduce((a,p)=>a+payments(p),0),revenue=sales.filter(s=>s.status!=='Em negociação').reduce((a,s)=>a+saleGross(s),0),received=sales.reduce((a,s)=>a+num(s.receivedAmount),0),sold=sales.reduce((a,s)=>a+num(s.shipped),0),reserved=sales.filter(s=>!['Entregue','Cancelada'].includes(s.status)).reduce((a,s)=>a+Math.max(num(s.reserved)-num(s.shipped),0),0),avgCost=approved?purchaseCost/approved:0,commission=sales.reduce((a,s)=>a+saleGross(s)*num(s.commissionPct)/100,0),extra=sales.reduce((a,s)=>a+num(s.extraCosts),0),estimatedCost=sold*avgCost,profit=revenue-estimatedCost-commission-extra,margin=revenue?profit/revenue*100:0,capitalTotal=capital.reduce((a,e)=>a+(e.movementType==='Retirada'?-1:1)*num(e.amount),0),stock=Math.max(approved-sold,0);return{purchases,sales,capital,clients,investors,purchasedQty,purchaseCost,approved,paidPurchases,revenue,received,sold,reserved,avgCost,profit,margin,capitalTotal,stock,stockValue:stock*avgCost,payable:Math.max(purchaseCost-paidPurchases,0),receivable:Math.max(revenue-received,0)}}
function group(items,key,value){return Object.entries(items.reduce((o,x)=>{const k=key(x)||'Não informado';o[k]=(o[k]||0)+value(x);return o},{})).sort((a,b)=>b[1]-a[1])}
function panel(title,rows){return`<article class="report-panel"><h2>${title}</h2>${rows.length?rows.map((r,i)=>`<div class="report-row"><span>${r.rank?`<b class="rank-number">${i+1}</b>`:''}${r.label}</span><strong>${r.value}</strong></div>`).join(''):'<div class="report-empty">Sem dados neste período.</div>'}</article>`}
function renderReports(){if(!$('#reportContent'))return;const d=data(),view=$('#reportView').value,suppliers=group(d.purchases,p=>p.supplier,p=>num(p.quantity)).slice(0,5),clientMap=new Map(d.clients.map(c=>[c.id,c.name])),clientRank=group(d.sales,s=>clientMap.get(s.clientId)||'Cliente não localizado',saleGross).slice(0,5),maxSupplier=suppliers[0]?.[1]||1;const alerts=[];if(d.capitalTotal-d.purchaseCost<0)alerts.push('Capital comprometido acima do capital registrado no período.');if(d.receivable>0)alerts.push(`${money(d.receivable)} ainda aguardando recebimento.`);if(d.payable>0)alerts.push(`${money(d.payable)} ainda aguardando pagamento a fornecedores.`);if(d.stock>0&&d.sales.length===0)alerts.push('Há estoque disponível, mas nenhuma venda registrada no período.');if(!alerts.length)alerts.push('Nenhum alerta crítico identificado nos dados atuais.');let html=`<div class="report-kpis"><article class="report-kpi"><span>Capital registrado</span><strong>${money(d.capitalTotal)}</strong></article><article class="report-kpi"><span>Valor em estoque</span><strong>${money(d.stockValue)}</strong></article><article class="report-kpi"><span>Faturamento</span><strong>${money(d.revenue)}</strong></article><article class="report-kpi"><span>Lucro estimado</span><strong>${money(d.profit)}</strong></article><article class="report-kpi"><span>Margem estimada</span><strong>${pct(d.margin)}</strong></article><article class="report-kpi"><span>Contas a receber</span><strong>${money(d.receivable)}</strong></article><article class="report-kpi"><span>Estoque físico</span><strong>${d.stock.toLocaleString('pt-BR',{maximumFractionDigits:2})} latas</strong></article><article class="report-kpi"><span>Vendas registradas</span><strong>${d.sales.length}</strong></article></div>`;
 html+=`<section class="report-section"><h2>Alertas gerenciais</h2>${alerts.map((a,i)=>`<div class="report-alert ${alerts.length===1&&!d.receivable&&!d.payable?'good':''}">${a}</div>`).join('')}</section>`;
 const financial=[{label:'Compras realizadas',value:money(d.purchaseCost)},{label:'Pagamentos a fornecedores',value:money(d.paidPurchases)},{label:'Contas a pagar',value:money(d.payable)},{label:'Recebimentos de clientes',value:money(d.received)},{label:'Contas a receber',value:money(d.receivable)},{label:'Custo médio por lata',value:money(d.avgCost)}];
 const stock=[{label:'Quantidade comprada',value:`${d.purchasedQty.toLocaleString('pt-BR')} latas`},{label:'Quantidade aprovada',value:`${d.approved.toLocaleString('pt-BR')} latas`},{label:'Quantidade enviada',value:`${d.sold.toLocaleString('pt-BR')} latas`},{label:'Quantidade reservada',value:`${d.reserved.toLocaleString('pt-BR')} latas`},{label:'Quantidade disponível',value:`${Math.max(d.stock-d.reserved,0).toLocaleString('pt-BR')} latas`}];
 const commercial=[{label:'Pedidos e vendas',value:d.sales.length},{label:'Clientes cadastrados',value:d.clients.length},{label:'Ticket médio',value:money(d.sales.length?d.revenue/d.sales.length:0)},{label:'Preço médio de venda',value:money(d.sold?d.revenue/d.sold:0)},{label:'Margem estimada',value:pct(d.margin)}];
 html+=`<section class="report-section report-grid">${view==='financial'?panel('Financeiro',financial):view==='commercial'?panel('Comercial',commercial):view==='stock'?panel('Estoque e lotes',stock):panel('Resumo financeiro',financial)+panel('Estoque e movimentação',stock)+panel('Desempenho comercial',commercial)}${panel('Ranking de fornecedores',suppliers.map(([label,v])=>({label,value:`${v.toLocaleString('pt-BR')} latas`,rank:true}))) }${panel('Ranking de clientes',clientRank.map(([label,v])=>({label,value:money(v),rank:true})))}</section>`;
 html+=`<section class="report-section"><article class="report-panel"><h2>Participação dos fornecedores</h2>${suppliers.length?suppliers.map(([name,v])=>`<div class="report-row"><div style="flex:1"><span>${name}</span><div class="report-bar"><i style="width:${Math.max(v/maxSupplier*100,4)}%"></i></div></div><strong>${v.toLocaleString('pt-BR')}</strong></div>`).join(''):'<div class="report-empty">Sem compras cadastradas.</div>'}</article></section>`;
 $('#reportContent').innerHTML=html;
}
install();addEventListener('storage',renderReports);window.renderReports=renderReports;
})();