const CACHE='natural-castanhas-v23';
const FILES=['./index.html','./styles.css','./ios-form-fix.css','./app.js','./sales.js','./financeiro.js','./resultados.js','./relatorios.js','./nucleo9-nome.js','./ios-form-fix.js','./nucleo3-integrado.js','./nucleo3-melhorias.js','./nucleo4-estoque.js','./nucleo8-link.js','./nucleo10-link.js','./nucleo11-usuarios.js','./nucleo12-link.js','./barra-inferior.js','./nucleo-8-transporte.html','./nucleo-10-documentos.html','./manifest.webmanifest'];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES)))});
self.addEventListener('activate',event=>{event.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key))))]))});
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url),isHome=event.request.mode==='navigate'&&(url.pathname.endsWith('/')||url.pathname.endsWith('/index.html'));
 if(isHome){event.respondWith((async()=>{let response;try{response=await fetch(event.request,{cache:'no-store'})}catch(error){response=await caches.match('./index.html')}let html=await response.text();if(!html.includes('ios-form-fix.css'))html=html.replace('</head>','<link rel="stylesheet" href="./ios-form-fix.css?v=23"></head>');const required=[['nucleo3-integrado.js','<script src="./nucleo3-integrado.js?v=23"></script>'],['nucleo3-melhorias.js','<script src="./nucleo3-melhorias.js?v=23"></script>'],['nucleo4-estoque.js','<script src="./nucleo4-estoque.js?v=23"></script>'],['financeiro.js','<script src="./financeiro.js?v=23"></script>'],['ios-form-fix.js','<script src="./ios-form-fix.js?v=23"></script>'],['resultados.js','<script src="./resultados.js?v=23"></script>'],['nucleo8-link.js','<script src="./nucleo8-link.js?v=23"></script>'],['relatorios.js','<script src="./relatorios.js?v=23"></script>'],['nucleo9-nome.js','<script src="./nucleo9-nome.js?v=23"></script>'],['nucleo10-link.js','<script src="./nucleo10-link.js?v=23"></script>'],['nucleo11-usuarios.js','<script src="./nucleo11-usuarios.js?v=23"></script>'],['nucleo12-link.js','<script src="./nucleo12-link.js?v=23"></script>'],['barra-inferior.js','<script src="./barra-inferior.js?v=23"></script>']];required.forEach(([name,tag])=>{if(!html.includes(name))html=html.replace('</body>',tag+'</body>')});return new Response(html,{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, no-cache, must-revalidate'}})})());return}
 if(url.origin===location.origin&&['script','style'].includes(event.request.destination)){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match(event.request)));return}
 event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)));
});